### ISSUE TITLE
SWEET cannot be found

### ISSUE THREAD

**Issue by Yongyao** [Yongyao/mudrod#2]
When starting the Web service, the following error message needs to be fixed.

```
https://raw.githubusercontent.com/ESIPFed/sweet/master/2.4/sweetAll.owl: Error: 
org.apache.jena.shared.DoesNotExistException: https://raw.githubusercontent.com/ESIPFed/sweet/master/2.4/sweetAll.owl
	at org.apache.jena.rdfxml.xmlinput.JenaReader.read(JenaReader.java:97)
	at org.apache.jena.rdf.model.impl.ModelCom.read(ModelCom.java:263)
	at org.apache.jena.ontology.impl.OntModelImpl.readDelegate(OntModelImpl.java:3090)
	at org.apache.jena.ontology.impl.OntModelImpl.read(OntModelImpl.java:2182)
	at gov.nasa.jpl.mudrod.ontology.process.LocalOntology.load(LocalOntology.java:133)
```

**Comment by Yongyao** [comment]
Fixed
